// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR3AO1gBVhJp2kViAnsFlvmGhZ4OxAm80',
    appId: '1:989718417949:web:946235eed95250dfdfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    authDomain: 'cinebyte-network.firebaseapp.com',
    storageBucket: 'cinebyte-network.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWYcFrKHqzBWCbqKojyjN2Gs_sQsaYY0',
    appId: '1:989718417949:android:f8161f5f2b84e173dfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    storageBucket: 'cinebyte-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOpodYkxyLw0FjVt1KM81aAPOAx-jN1U',
    appId: '1:989718417949:ios:88475c747278621fdfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    storageBucket: 'cinebyte-network.appspot.com',
    iosBundleId: 'com.example.cinebyteNetworkApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOpodYkxyLw0FjVt1KM81aAPOAx-jN1U',
    appId: '1:989718417949:ios:89b3628f37e56d4edfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    storageBucket: 'cinebyte-network.appspot.com',
    iosBundleId: 'com.example.cinebyteNetworkApplication.RunnerTests',
  );
}
